### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kuletxcore** [AmyTsurimi/Girls_Frontline_Black_Ops_-_Phase-2#1]
- [x] Convert all lines from the main game to GFL-related lines
- [x] transfer all the rewritten lines to the .str files that the mod tools can read
- [x] encode some One Time Pads for Revelations easter egg
- [x] implement `YOUKILLEDUMPFORTY` easter egg on top of the existing `XREZNOVXXISXDEADX` easter egg
- [x] Make the Part 2 of the `YOUKILLEDUMPFORTY` easter egg and encode it using Vignere
- [x] recreate some cutscenes using in-game footage
- [x] "upscale" and convert all bik files to 60fps using Flowframes

**Comment by kuletxcore** [comment]
Complete! Just need proofing and error-checking...
